apiVersion: apps/v1
kind: Deployment
metadata:
  name: lockbox-gateway
spec:
  selector:
    matchLabels:
      app: lockbox-gateway
  template:
    metadata:
      labels:
        app: lockbox-gateway
    spec:
      containers:
      - name: lockbox-gateway
        image: rikdegoede/lockbox-gateway:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: lockbox-gateway
spec:
  type: LoadBalancer
  selector:
    app: lockbox-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
