apiVersion: v1
kind: Service
metadata:
  name: lockbox-notification-service
spec:
  type: LoadBalancer
  selector:
    app: lockbox-notification-service
  ports:
    - protocol: TCP
      name: api-port
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: metric-port
      port: 1234
      targetPort: 1234
