apiVersion: v1
kind: Service
metadata:
  name: lockbox-notification-service
spec:
  type: ClusterIP     # TODO: Should be exposed extrenally using LoadBalancer
  selector:
    app: lockbox-notification-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
