apiVersion: apps/v1
kind: Deployment
metadata:
  name: lockbox-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lockbox-notification-service
  template:
    metadata:
      labels:
        app: lockbox-notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1234"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: lockbox-notification-service
        image: rikdegoede/lockbox-notification-service:latest 
        ports:
          - containerPort: 8080
          - containerPort: 1234
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
          - name: MONGODB_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: lockbox-secrets
                key: mongodb-conn-string
          
          - name: RABBITMQ_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: lockbox-secrets
                key: rabbitmq-conn-string

---

apiVersion: v1
kind: Service
metadata:
  name: lockbox-notification-service
spec:
  type: LoadBalancer
  selector:
    app: lockbox-notification-service
  ports:
    - protocol: TCP
      name: api-port
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: metric-port
      port: 1234
      targetPort: 1234
