apiVersion: apps/v1
kind: Deployment
metadata:
  name: lockbox-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lockbox-notification-service
  template:
    metadata:
      labels:
        app: lockbox-notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1234"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: lockbox-notification-service
        image: rikdegoede/lockbox-notification-service:latest 
        ports:
          - containerPort: 8080
          - containerPort: 1234
        env:
          - name: MONGODB_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: lockbox-secrets
                key: mongodb-conn-string
          
          - name: RABBITMQ_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: lockbox-secrets
                key: rabbitmq-conn-string
