apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-test
  template:
    metadata:
      labels:
        app: rabbitmq-test
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.11-management
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: quest
          - name: RABBITMQ_DEFAULT_PASS
            value: quest
        ports:
          - containerPort: 5672   # AMQP
          - containerPort: 15672  # Management UI
        volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          emptyDir: {}    # ephemeral for testing
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-test
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-test
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672

