server:
  extraScrapeConfigs:
    - job_name: 'notification-service'
      scrape_interval: 15s
      scrape_timeout: 10s
      static_configs:
        - targets: ['lockbox-notification-service.default.svc.cluster.local:1234']
          labels: 
            group: 'development'
      metrics_path: '/metrics'

